language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                   ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y purge libgraphviz-dev ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                             ; fi

install:
- sudo pip install -r ./python/requirements.txt
- sudo pip install nose

script: 
- make NO_GRAPHVIZ=1 NO_RAW_PARSER=1
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/lib ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DYLD_FALLBACK_LIBRARY_PATH=${DYLD_FALLBACK_LIBRARY_PATH}:${PWD}/lib ; fi
- cd python
- python setup.py build_ext --inplace --no_graphviz --no_raw_parser
- nosetests -s -v