language: python

python:
- "2.7"
- "3.4"

before_install:
- sudo apt-get update
- sudo apt-get -y purge libgraphviz-dev

install:
- pip install -r ./python/requirements.txt

script: 
- make NO_GRAPHVIZ=1 NO_RAW_PARSER=1
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:${PWD}/lib
- cd python
- python setup.py build_ext --inplace --no_graphviz --no_raw_parser
- nosetests -s -v