language: python

python:
- "2.7"
- "3.4"

before_install:
- sudo apt-get update
- sudo apt-get -y purge libgraphviz-dev
- sudo apt-get -y install m4

install:
- pip install -r ./python/requirements.txt

script: 
- mkdir m4
- autoreconf -fvi
- ./configure
- make
- make check
- sudo make install
- export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib
- cd python
- python setup.py build_ext --inplace
- nosetests -s -v