language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update                   ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y purge libgraphviz-dev ; fi
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get -y install m4            ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then brew update                             ; fi

install:
- sudo pip install -r ./python/requirements.txt
- sudo pip install nose

script: 
- mkdir m4
- autoreconf -fvi
- ./configure
- make
- make check
- sudo make install
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then export LD_LIBRARY_PATH=${LD_LIBRARY_PATH}:/usr/local/lib                     ; fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then export DYLD_FALLBACK_LIBRARY_PATH=${DYLD_FALLBACK_LIBRARY_PATH}:/usr/local/lib ; fi
- cd python
- python setup.py build_ext --inplace
- nosetests -s -v