language: c

install:
- sudo apt-get update
- sudo apt-get -y purge libgraphviz-dev libgraphviz graphviz
- sudo apt-get -y install m4

script: 
- mkdir m4
- autoreconf -fvi
- ./configure
- make
- make check
- make install