language: c

os:
- osx
- linux

before_install:
- if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then 
    sudo apt-get update;
    sudo apt-get -y purge libgraphviz-dev; 
    sudo apt-get -y install m4;
  fi
- if [[ "$TRAVIS_OS_NAME" == "osx" ]]; then 
    brew update;
  fi

install:
- sudo pip install -r ./python/requirements.txt
- sudo pip install nose

script: 
- ./autogen.sh
- ./configure
- make
- make check
- sudo make install
- cd python
- python setup.py build_ext --inplace
- nosetests -s -v